version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.80.0/24
services:
  webserver:
    image: new:1
    stdin_open: true
    tty: true
    hostname: apache
    domainname: example.com
    ports:
     - '7080:80'
    networks:
      app_net:
        ipv4_address: 192.168.80.10
   
    
      
  
